server:
  port: ${CUSTOM.SERVER.PORT:9090}
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
    fetchRegistry: true
resilience4j:
  circuitbreaker:
    configs:
      mitocodeCircuitbreakerProduct:
        slidingWindowSize: 10
        failureRateThreshold: 75
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 10
    instances:
      product-cb:
        base-config: mitocodeCircuitbreakerProduct
  timelimiter:
    configs:
      mitocodeTimeLimiterProduct:
        timeoutDuration: 1s
    instances:
      product-time:
        base-config: mitocodeTimeLimiterProduct
spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/**
          filters:
            # - name: CircuitBreaker
              # args:
                # name: product-cb
                # statusCodes: 400, 401, 403, 500, 503, 504
                # fallbackUri: forward:/fallback
            - StripPrefix=2

        - id: product-query-service
          uri: lb://product-query-service
          predicates:
            - Path=/api/product-query-service/**
            - Weight=product-query-group, 20
          filters:
            - StripPrefix=2

        - id: product-query-service-v2
          uri: lb://product-query-service
          predicates:
            - Path=/api/product-query-service/**
            - Weight=product-query-group, 80
          filters:
            - StripPrefix=2
            
        - id: fallback
          uri: http://localhost:9002/product/false
          predicates:
            - Path=/fallback
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2

mitocode:
  security:
    signKey: b4f19a90798bfcededcf89c2f76baf65739988bd15cb76a317baeca6c4a4eb1e915b40e620bbb8601e4ca981d9ca036c754ebdf9ece1c9c95fcb2ca1f526f8c588065e9e350534afad30f142906f76757bb6673cc0741c2fe7f83bbeb0060eb2b7d6fc9a63fdc9f644a867327c05fc9c37d17d549fdcdb2970a075fce4524afe8fbd6ffa231c8038f94cfa0eb98c6ff3a61efac2151b8c0b915c0d7456f95015340490e1730ff4b997745849ec4a3cc76f2a83dbf32af3b396f588d8ca7ad60252997b01f7f7fb4edd2feaf730159190f3809662fc242183f9f71b955c888b41